{
    "geocoding": {
        "version": "0.2",
        "attribution": "https://openrouteservice.org/terms-of-service/#attribution-geocode",
        "query": {
            "text": "14 acton place",
            "size": 10,
            "private": False,
            "boundary.country": ["GBR"],
            "lang": {
                "name": "English",
                "iso6391": "en",
                "iso6393": "eng",
                "via": "default",
                "defaulted": True,
            },
            "querySize": 20,
            "parser": "libpostal",
            "parsed_text": {"housenumber": "14", "street": "acton place"},
        },
        "engine": {"name": "Pelias", "author": "Mapzen", "version": "1.0"},
        "timestamp": 1709025277921,
    },
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [-1.581032, 54.994644]},
            "properties": {
                "id": "polyline:1641112",
                "gid": "openstreetmap:street:polyline:1641112",
                "layer": "street",
                "source": "openstreetmap",
                "source_id": "polyline:1641112",
                "name": "Acton Place",
                "street": "Acton Place",
                "confidence": 0.8,
                "match_type": "fallback",
                "accuracy": "centroid",
                "country": "United Kingdom",
                "country_gid": "whosonfirst:country:85633159",
                "country_a": "GBR",
                "macroregion": "England",
                "macroregion_gid": "whosonfirst:macroregion:404227469",
                "region": "Tyne & Wear",
                "region_gid": "whosonfirst:region:1360698601",
                "county": "Newcastle upon Tyne",
                "county_gid": "whosonfirst:county:1360698961",
                "county_a": "NET",
                "locality": "Newcastle upon Tyne",
                "locality_gid": "whosonfirst:locality:101750617",
                "continent": "Europe",
                "continent_gid": "whosonfirst:continent:102191581",
                "label": "Acton Place, Newcastle upon Tyne, England, United Kingdom",
            },
            "bbox": [-1.581284, 54.994471, -1.58102, 54.994761],
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [-2.156484, 53.259821]},
            "properties": {
                "id": "polyline:2309574",
                "gid": "openstreetmap:street:polyline:2309574",
                "layer": "street",
                "source": "openstreetmap",
                "source_id": "polyline:2309574",
                "name": "Acton Place",
                "street": "Acton Place",
                "confidence": 0.8,
                "match_type": "fallback",
                "accuracy": "centroid",
                "country": "United Kingdom",
                "country_gid": "whosonfirst:country:85633159",
                "country_a": "GBR",
                "macroregion": "England",
                "macroregion_gid": "whosonfirst:macroregion:404227469",
                "region": "Cheshire",
                "region_gid": "whosonfirst:region:1360698537",
                "county": "Cheshire East",
                "county_gid": "whosonfirst:county:1360698929",
                "county_a": "CHE",
                "locality": "Macclesfield",
                "locality_gid": "whosonfirst:locality:101750519",
                "continent": "Europe",
                "continent_gid": "whosonfirst:continent:102191581",
                "label": "Acton Place, Macclesfield, England, United Kingdom",
            },
            "bbox": [-2.156584, 53.259636, -2.156384, 53.260006],
        },
    ],
    "bbox": [-2.156584, 53.259636, -1.58102, 54.994761],
}
